name: CD with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Debug SSH Connection
        run: |
          echo "Testing SSH connection..."
          ssh -o StrictHostKeyChecking=no -vvv -i <(echo "${{ secrets.SSH_PRIVATE_KEY }}") \
          ${{ secrets.DEPLOY_SERVER_USER }}@${{ secrets.DEPLOY_SERVER_IP }} "echo 'SSH Connection Successful'"
          
      - name: Deploy on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_SERVER_IP }}
          username: ${{ secrets.DEPLOY_SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Checking SSH access inside SSH session..."
            whoami
            hostname
            ls -la ~/.ssh
            cat ~/.ssh/authorized_keys | grep "$(echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-keygen -y -f -)"
            echo "Proceeding with deployment..."
            cd /home/vagrant/
            docker compose down
            docker images prune -f
            docker compose pull
            docker compose up -d --force-recreate
