name: CI with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image for Frontend
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend

      - name: Build and Push Docker Image for Backend 
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend
