name: CICD pipeline for HIDR

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install and build
        working-directory: ./frontend
        run: |
            npm install
            npm run build

      - name: Zip build
        run: zip -r build.zip .

      - name: Deploy to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USER }}
          server: ${{ secrets.SFTP_SERVER }}
          port: ${{ secrets.SFTP_PORT }}
          ssh_private_key: ${{ secrets.SFTP_KEY }}
          local_path: build.zip
          remote_path: /var/www/html/frontend/
          sftpArgs: -o ConnectTimeout=5

      - name: Unzip on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USER }}
          key: ${{ secrets.SFTP_KEY }}
          password: "sangam123"
          port: ${{ secrets.SFTP_PORT }}
          script: |
            cd /var/www/html/frontend
            unzip build.zip
            cd frontend
            pm2 start npm --name wanderlust-frontend -- run dev -- --PORT 80
            rm -rf /var/www/html/frontend/build.zip                                                                                                                                                                        
