name: CICD pipeline for HIDR

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 22

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Install and build
        working-directory: ./frontend
        run: |
            npm install
            npm run build

      - name: Install ESLint
        run: npm install eslint@9.10.0 --save-dev
        working-directory: ./frontend
        
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true            

      - name: Zip build
        run: zip -r build.zip .

      - name: Deploy to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USER }}
          server: ${{ secrets.SFTP_SERVER }}
          port: ${{ secrets.SFTP_PORT }}
          ssh_private_key: ${{ secrets.SFTP_KEY }}
          local_path: build.zip
          remote_path: /var/www/html/frontend/
          sftpArgs: -o ConnectTimeout=5

      - name: Unzip on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USER }}
          key: ${{ secrets.SFTP_KEY }}
          port: ${{ secrets.SFTP_PORT }}
          script: |
            cd /var/www/html/frontend
            unzip -o build.zip
            cd frontend
            pip install pm2 -g
            pm2 start npm --name wanderlust-frontend -- run dev -- --PORT 80
            rm -rf /var/www/html/frontend/build.zip                                                                                                                                                                        
